
services:
  proxy:
    build: ./proxy
    ports:
      - "3128:3128"
    volumes:
      - ./proxy/config:/etc/squid
      - ./proxy/blacklists:/etc/squid/blacklists
      - ./proxy/logs:/var/log/squid  
    restart: always  
    command: ["bash", "-c", "tail -f /dev/null"]  
    deploy:
      resources:
        limits:
          memory: 512M
