version: '3.8'

services:
  proxy:
    build: ./proxy
    ports:
      - "3128:3128"
    volumes:
      - ./proxy/config:/etc/squid
      - ./proxy/blacklists:/etc/squid/blacklists
      - ./proxy/logs:/var/log/squid  
    restart: always  
    command: ["bash", "-c", "tail -f /dev/null"]  
    
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:5000"
    volumes:
      - ./frontend:/app
