name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: false
          tags: user/backend:latest

      # - name: Build and push frontend
      #   uses: docker/build-push-action@v2
      #   with:
      #    context: ./frontend
      #    push: false
      #    tags: user/frontend:latest

      - name: Build and push proxy
        uses: docker/build-push-action@v2
        with:
          context: ./proxy
          push: false
          tags: user/proxy:latest

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: docker-compose build

     
