name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer la version de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Utilisez la version de Python que vous souhaitez

      # Installer les dépendances nécessaires pour l'exécution de flake8
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # Linting avec flake8 pour vérifier les erreurs dans votre script
      - name: Lint with flake8
        run: flake8 autoYoutubeApi/autoYtProj.py --max-line-length=220

  