name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: docker-compose build

      - name: Run backend tests
        run: |
          docker-compose up -d backend
          sleep 10  # Attendre que le backend soit prêt
          docker-compose exec backend pytest
        env:
          CI: true

      - name: Run frontend tests
        run: |
          docker-compose up -d frontend
          sleep 10  # Attendre que le frontend soit prêt
          docker-compose exec frontend npm test
        env:
          CI: true

      - name: Run proxy tests
        run: |
          docker-compose up -d proxy
          sleep 10  # Attendre que le proxy soit prêt
          # Ajouter les tests spécifiques pour le proxy ici
        env:
          CI: true
