name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest

      - name: Run backend tests
        run: |
          docker-compose up -d backend
          docker exec backend pytest

      - name: Run frontend tests
        run: |
          docker-compose up -d frontend
          docker exec frontend npm test

      - name: Run proxy tests
        run: |
          docker-compose up -d proxy
          # Ajouter les tests spécifiques pour le proxy ici
